### ISSUE TITLE
Incompatibility with Kibana 7.6.x

### ISSUE THREAD

**Issue by donovanmuller** [novomatic-tech/keycloak-kibana#40]
After updating the Kibana version to `7.6.1` wherever necessary and running `yarn start` you get the following error:

```console
...
server    log   [12:55:33.228] [fatal][root] TypeError: server.registerCapabilitiesModifier is not a function
    at configureAllowedAppsNavLinks (/Users/donovan/dev/absa/bcp/stackoverflow/elastic/keycloak-kibana/kibana/plugins/keycloak-kibana/index.js:92:10)
    at Plugin.init [as externalInit] (/Users/donovan/dev/absa/bcp/stackoverflow/elastic/keycloak-kibana/kibana/plugins/keycloak-kibana/index.js:249:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
...
```

**Comment by Finu** [comment]
Unfortunately, currently we don't plan to upgrade this plugin to work with kibana 7.6 as it would required to much work from our side and internal code of kibana change to fast as 7.x line is for migrating from old angular code to react and new platform api.

**Comment by donovanmuller** [comment]
Thanks, what does that mean for the future of this project? 
I.e. will you continue to support this when the API's are more stable or will you not support anything  Kibana version after `7.5.x`?

**Comment by Finu** [comment]
We gonna stuck with this version until 8.0.0 will be release. As this plugin has to be rewritten from scratch once new kibana plugin API is stable.
