### ISSUE TITLE
Error with Kibana 7.9.1 - "server.registerCapabilitiesModifier is not a function"

### ISSUE THREAD

**Issue by enlight3d** [novomatic-tech/keycloak-kibana#51]
Hello, I followed your guide to build the plugin for a more recent version of Kibana (we're using v7.9.1 here). I managed to do it correctly and added the required config you provide as example for both Kibana and Keycloak, but Kibana doesn't seem to want to load your plugin. I get this error :

```
 FATAL  TypeError: server.registerCapabilitiesModifier is not a function,
{"type":"log","@timestamp":"2020-12-15T10:08:14Z","tags":["info","plugins-system"],"pid":6,"message":"Stopping all plugins."},
{"type":"log","@timestamp":"2020-12-15T10:08:14Z","tags":["fatal","root"],"pid":6,"message":"TypeError: server.registerCapabilitiesModifier is not a function\n    at configureAllowedAppsNavLinks (/usr/share/kibana/plugins/keycloak-kibana/index.js:92:10)\n    at Plugin.init [as externalInit] (/usr/share/kibana/plugins/keycloak-kibana/index.js:249:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
```

I've searched for infos, it seems that the function `registerCapabilitiesModifier` has been deprecated and/or is part of a legacy API.

Could you provide some help here ? That would be really appreciated !

**Comment by Finu** [comment]
Unfortunately - this plugin is not compatible with kibana higher than 7.5.0

**Comment by enlight3d** [comment]
Any input why ? no way to make it compatible with a higher version ?

**Comment by hamid512** [comment]
i had to force myself to use 7.5.0

**Comment by Finu** [comment]
We tried to update it to 7.6 but got stuck on some problems.
Now se don't have enought resources to work on it - and version 7.5.0 is currently enought for our needs.
But if you want to contribute feel free to create PR.
